version: "3.11.5"

services:
  backend:
    build: .
    ports:
      - "5000:5000"  # проброс порта 5000
    environment:
      - PYTHONPATH=/app
    volumes:
      - C:/Users/Admin/Desktop/Study/docker_cifra/data/weights:/app/weights
      - C:/Users/Admin/Desktop/Study/docker_cifra/data/camera_videos/camera_records:/app/video
      - C:/Users/Admin/Desktop/Study/docker_cifra/src/model:/app/tracker